//! Normalizador de SQL entre dialetos. Pipeline do import:
//!   `detect_dialect(sql)` → descobre origem pelo conteúdo
//!   `normalize_for(sql, target)` → traduz se source != target
//!
//! Escopo: cobrir o que `mysqldump`/`pg_dump` geram pra casos comuns.
//! Não é um parser completo — regex + scanner string-aware.
//!
//! Direções:
//!   MySQL → PostgreSQL : robusto (cobre maioria dos dumps)
//!   PostgreSQL → MySQL : básico (tipos principais + identifier quoting)
//!   MySQL → MySQL / PG → PG : pass-through
//!   Unknown → X : pass-through (risco do usuário)

use std::sync::OnceLock;

use regex::Regex;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Dialect {
    Mysql,
    Postgres,
    Unknown,
}

impl Dialect {
    pub fn from_driver_name(s: &str) -> Self {
        match s {
            "mysql" | "mariadb" => Dialect::Mysql,
            "postgres" | "postgresql" => Dialect::Postgres,
            _ => Dialect::Unknown,
        }
    }
}

/// Scaneia até 16KB do início do SQL procurando tokens que denunciam
/// o dialeto. Heurística pragmática — dumps reais dão "fingerprint"
/// claro logo no header.
pub fn detect_dialect(sql: &str) -> Dialect {
    let sample = &sql[..sql.len().min(16 * 1024)];
    // Backtick quoting é muito específico do MySQL.
    if sample.contains('`') {
        return Dialect::Mysql;
    }
    let upper = sample.to_uppercase();
    // MySQL fingerprints.
    let mysql_markers = [
        " ENGINE=",
        " ENGINE =",
        "AUTO_INCREMENT",
        "DEFAULT CHARSET",
        "CHARACTER SET=",
        "ROW_FORMAT=",
        "LOCK TABLES",
        "UNLOCK TABLES",
        "TINYINT(1)",
        "MEDIUMINT",
        "LONGTEXT",
        "MEDIUMTEXT",
        "LONGBLOB",
        "MEDIUMBLOB",
        "TINYBLOB",
        "/*!",
        "SET NAMES",
        "UNSIGNED",
    ];
    if mysql_markers.iter().any(|m| upper.contains(m)) {
        return Dialect::Mysql;
    }
    // PG fingerprints.
    let pg_markers = [
        "SERIAL",
        "BIGSERIAL",
        "BYTEA",
        "JSONB",
        "TIMESTAMPTZ",
        "TIMESTAMP WITH TIME ZONE",
        "TIMESTAMP WITHOUT TIME ZONE",
        "::", // casts PG-specific
        "GENERATED BY DEFAULT AS IDENTITY",
        "GENERATED ALWAYS AS IDENTITY",
        "CREATE SCHEMA",
        "SET search_path",
        "OWNER TO",
    ];
    if pg_markers.iter().any(|m| upper.contains(m)) {
        return Dialect::Postgres;
    }
    Dialect::Unknown
}

/// Normaliza o SQL pra rodar no target. Se source == target (ou
/// indetectável), retorna sem mexer. O import chama isso antes de
/// cada execute quando acha que precisa.
pub fn normalize_for(sql: &str, source: Dialect, target: Dialect) -> String {
    match (source, target) {
        (Dialect::Mysql, Dialect::Postgres) => mysql_to_postgres(sql),
        (Dialect::Postgres, Dialect::Mysql) => postgres_to_mysql(sql),
        _ => sql.to_string(),
    }
}

// ---------------------------------------------------------------- MySQL→PG

fn mysql_to_postgres(sql: &str) -> String {
    let step1 = rewrite_backticks_to_double_quotes(sql);
    let mut out = step1;
    for (re, rep) in mysql_to_pg_transforms() {
        out = re.replace_all(&out, *rep).to_string();
    }
    out = strip_character_set_collate_inline(&out);
    out = auto_increment_to_identity(&out);
    out
}

/// `` `foo` `` → `"foo"` respeitando strings aspeadas.
fn rewrite_backticks_to_double_quotes(sql: &str) -> String {
    let mut out = String::with_capacity(sql.len());
    let bytes = sql.as_bytes();
    let mut i = 0;
    let len = bytes.len();
    while i < len {
        let b = bytes[i];
        if b == b'\'' || b == b'"' {
            let quote = b;
            out.push(b as char);
            i += 1;
            while i < len {
                let c = bytes[i];
                if c == b'\\' && i + 1 < len {
                    out.push(c as char);
                    out.push(bytes[i + 1] as char);
                    i += 2;
                    continue;
                }
                if c == quote {
                    if i + 1 < len && bytes[i + 1] == quote {
                        out.push(c as char);
                        out.push(c as char);
                        i += 2;
                        continue;
                    }
                    out.push(c as char);
                    i += 1;
                    break;
                }
                out.push(c as char);
                i += 1;
            }
            continue;
        }
        if b == b'`' {
            i += 1;
            let mut ident = String::new();
            while i < len {
                let c = bytes[i];
                if c == b'`' {
                    if i + 1 < len && bytes[i + 1] == b'`' {
                        ident.push('`');
                        i += 2;
                        continue;
                    }
                    i += 1;
                    break;
                }
                ident.push(c as char);
                i += 1;
            }
            out.push('"');
            out.push_str(&ident.replace('"', "\"\""));
            out.push('"');
            continue;
        }
        if b == b'#' {
            out.push_str("--");
            i += 1;
            continue;
        }
        out.push(b as char);
        i += 1;
    }
    out
}

fn mysql_to_pg_transforms() -> &'static [(Regex, &'static str)] {
    static CELL: OnceLock<Vec<(Regex, &'static str)>> = OnceLock::new();
    CELL.get_or_init(|| {
        vec![
            (Regex::new(r"(?i)\s*ENGINE\s*=\s*\w+").unwrap(), ""),
            (Regex::new(r"(?i)\s*DEFAULT\s+CHARSET\s*=\s*\w+").unwrap(), ""),
            (Regex::new(r"(?i)\s*CHARACTER\s+SET\s*=\s*\w+").unwrap(), ""),
            (Regex::new(r"(?i)\s*DEFAULT\s+COLLATE\s*=\s*\w+").unwrap(), ""),
            (Regex::new(r"(?i)\s*COLLATE\s*=\s*\w+").unwrap(), ""),
            (Regex::new(r"(?i)\s*ROW_FORMAT\s*=\s*\w+").unwrap(), ""),
            (Regex::new(r"(?i)\s*AUTO_INCREMENT\s*=\s*\d+").unwrap(), ""),
            (Regex::new(r"(?i)\s*COMMENT\s*=\s*'(?:[^']|'')*'").unwrap(), ""),
            // MySQL conditional comments: `/*!40000 ... */` — mantém o conteúdo.
            (Regex::new(r"/\*!\d*\s*").unwrap(), ""),
            (Regex::new(r"\*/").unwrap(), ""),
            // Types.
            (Regex::new(r"(?i)\btinyint\s*\(\s*1\s*\)").unwrap(), "BOOLEAN"),
            (Regex::new(r"(?i)\btinyint(?:\s*\(\s*\d+\s*\))?").unwrap(), "SMALLINT"),
            (Regex::new(r"(?i)\bmediumint(?:\s*\(\s*\d+\s*\))?").unwrap(), "INTEGER"),
            (Regex::new(r"(?i)\bint\s*\(\s*\d+\s*\)").unwrap(), "INTEGER"),
            (Regex::new(r"(?i)\bbigint\s*\(\s*\d+\s*\)").unwrap(), "BIGINT"),
            (Regex::new(r"(?i)\bsmallint\s*\(\s*\d+\s*\)").unwrap(), "SMALLINT"),
            (Regex::new(r"(?i)\bdatetime\b").unwrap(), "TIMESTAMP"),
            (Regex::new(r"(?i)\bmediumtext\b").unwrap(), "TEXT"),
            (Regex::new(r"(?i)\blongtext\b").unwrap(), "TEXT"),
            (Regex::new(r"(?i)\btinytext\b").unwrap(), "TEXT"),
            (Regex::new(r"(?i)\btinyblob\b").unwrap(), "BYTEA"),
            (Regex::new(r"(?i)\bmediumblob\b").unwrap(), "BYTEA"),
            (Regex::new(r"(?i)\blongblob\b").unwrap(), "BYTEA"),
            (Regex::new(r"(?i)\bblob\b").unwrap(), "BYTEA"),
            // ENUM('a','b') / SET('a','b') → TEXT.
            (Regex::new(r"(?is)\b(?:ENUM|SET)\s*\([^)]*\)").unwrap(), "TEXT"),
            // Limpa UNSIGNED / ZEROFILL.
            (Regex::new(r"(?i)\s+UNSIGNED\b").unwrap(), ""),
            (Regex::new(r"(?i)\s+ZEROFILL\b").unwrap(), ""),
            // ON UPDATE CURRENT_TIMESTAMP — PG precisaria de trigger.
            (
                Regex::new(
                    r"(?i)\s+ON\s+UPDATE\s+CURRENT_TIMESTAMP(?:\(\s*\d*\s*\))?",
                )
                .unwrap(),
                "",
            ),
            // USING BTREE/HASH — PG infere.
            (Regex::new(r"(?i)\s+USING\s+(BTREE|HASH)\b").unwrap(), ""),
            // KEY/INDEX/FULLTEXT dentro de CREATE TABLE — linha inteira fora.
            (
                Regex::new(
                    r#"(?im)^\s*(?:KEY|INDEX|FULLTEXT\s+KEY|FULLTEXT\s+INDEX|SPATIAL\s+KEY|SPATIAL\s+INDEX)\s+"?\w+"?\s*\([^)]*\),?\s*$"#,
                )
                .unwrap(),
                "",
            ),
            // LOCK/UNLOCK TABLES, SET NAMES — MySQL-only.
            (Regex::new(r"(?i)\bLOCK\s+TABLES\b[^;]*;").unwrap(), ""),
            (Regex::new(r"(?i)\bUNLOCK\s+TABLES\s*;").unwrap(), ""),
            (Regex::new(r"(?i)\bSET\s+NAMES\s+\w+\s*;").unwrap(), ""),
            // MySQL string escape \' → ANSI ''.
            (Regex::new(r"\\'").unwrap(), "''"),
            // Trailing comma antes de `)` — sobra de KEY removido.
            (Regex::new(r",\s*\)").unwrap(), "\n)"),
        ]
    })
}

fn strip_character_set_collate_inline(sql: &str) -> String {
    static CELL: OnceLock<Vec<Regex>> = OnceLock::new();
    let patterns = CELL.get_or_init(|| {
        vec![
            Regex::new(r"(?i)\s+CHARACTER\s+SET\s+\w+").unwrap(),
            Regex::new(r"(?i)\s+CHARSET\s+\w+").unwrap(),
            Regex::new(r"(?i)\s+COLLATE\s+\w+").unwrap(),
        ]
    });
    let mut out = sql.to_string();
    for re in patterns {
        out = re.replace_all(&out, "").to_string();
    }
    out
}

fn auto_increment_to_identity(sql: &str) -> String {
    static CELL: OnceLock<Regex> = OnceLock::new();
    let re = CELL.get_or_init(|| Regex::new(r"(?i)\s+AUTO_INCREMENT\b").unwrap());
    re.replace_all(sql, " GENERATED BY DEFAULT AS IDENTITY")
        .to_string()
}

// ---------------------------------------------------------------- PG→MySQL

fn postgres_to_mysql(sql: &str) -> String {
    // 1. `"foo"` → `` `foo` `` (mas respeita strings).
    let step1 = rewrite_double_quotes_to_backticks(sql);
    let mut out = step1;
    for (re, rep) in pg_to_mysql_transforms() {
        out = re.replace_all(&out, *rep).to_string();
    }
    out
}

fn rewrite_double_quotes_to_backticks(sql: &str) -> String {
    // PG usa "..." pra identificadores E também pra strings em alguns
    // contextos (quando ANSI_QUOTES). Aqui assumimos o padrão de dump:
    // strings em '...', identificadores em "...". Transform 1-pra-1.
    let mut out = String::with_capacity(sql.len());
    let bytes = sql.as_bytes();
    let mut i = 0;
    let len = bytes.len();
    while i < len {
        let b = bytes[i];
        if b == b'\'' {
            // String — copia até fechar.
            out.push('\'');
            i += 1;
            while i < len {
                let c = bytes[i];
                if c == b'\\' && i + 1 < len {
                    out.push(c as char);
                    out.push(bytes[i + 1] as char);
                    i += 2;
                    continue;
                }
                if c == b'\'' {
                    if i + 1 < len && bytes[i + 1] == b'\'' {
                        out.push('\'');
                        out.push('\'');
                        i += 2;
                        continue;
                    }
                    out.push('\'');
                    i += 1;
                    break;
                }
                out.push(c as char);
                i += 1;
            }
            continue;
        }
        if b == b'"' {
            // Identificador → backtick.
            i += 1;
            let mut ident = String::new();
            while i < len {
                let c = bytes[i];
                if c == b'"' {
                    if i + 1 < len && bytes[i + 1] == b'"' {
                        ident.push('"');
                        i += 2;
                        continue;
                    }
                    i += 1;
                    break;
                }
                ident.push(c as char);
                i += 1;
            }
            out.push('`');
            out.push_str(&ident.replace('`', "``"));
            out.push('`');
            continue;
        }
        out.push(b as char);
        i += 1;
    }
    out
}

fn pg_to_mysql_transforms() -> &'static [(Regex, &'static str)] {
    static CELL: OnceLock<Vec<(Regex, &'static str)>> = OnceLock::new();
    CELL.get_or_init(|| {
        vec![
            // Types.
            (Regex::new(r"(?i)\bbigserial\b").unwrap(), "BIGINT AUTO_INCREMENT"),
            (Regex::new(r"(?i)\bserial\b").unwrap(), "INT AUTO_INCREMENT"),
            (Regex::new(r"(?i)\bbytea\b").unwrap(), "BLOB"),
            (Regex::new(r"(?i)\bjsonb\b").unwrap(), "JSON"),
            (Regex::new(r"(?i)\btimestamptz\b").unwrap(), "TIMESTAMP"),
            (
                Regex::new(r"(?i)\btimestamp\s+with\s+time\s+zone\b").unwrap(),
                "TIMESTAMP",
            ),
            (
                Regex::new(r"(?i)\btimestamp\s+without\s+time\s+zone\b").unwrap(),
                "DATETIME",
            ),
            (
                Regex::new(r"(?i)\btime\s+with\s+time\s+zone\b").unwrap(),
                "TIME",
            ),
            (
                Regex::new(r"(?i)\btime\s+without\s+time\s+zone\b").unwrap(),
                "TIME",
            ),
            (Regex::new(r"(?i)\bdouble\s+precision\b").unwrap(), "DOUBLE"),
            (Regex::new(r"(?i)\bboolean\b").unwrap(), "TINYINT(1)"),
            // IDENTITY → AUTO_INCREMENT.
            (
                Regex::new(r"(?i)\s+GENERATED\s+(BY\s+DEFAULT|ALWAYS)\s+AS\s+IDENTITY(?:\s*\([^)]*\))?").unwrap(),
                " AUTO_INCREMENT",
            ),
            // `::type` cast — remove (MySQL usa CAST() ou conversão implícita).
            (Regex::new(r"::\s*\w+(?:\s*\(\s*\d+\s*(?:,\s*\d+)?\s*\))?").unwrap(), ""),
            // `CREATE SCHEMA` → `CREATE DATABASE`.
            (Regex::new(r"(?i)\bCREATE\s+SCHEMA\b").unwrap(), "CREATE DATABASE"),
            // `SET search_path TO ...;` → ignora.
            (Regex::new(r"(?i)\bSET\s+search_path\s+TO[^;]*;").unwrap(), ""),
            // `OWNER TO ...` — sem análogo simples; strip.
            (Regex::new(r"(?i)\s+OWNER\s+TO\s+\w+").unwrap(), ""),
        ]
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dialect_from_driver_name_maps_known() {
        assert_eq!(Dialect::from_driver_name("mysql"), Dialect::Mysql);
        assert_eq!(Dialect::from_driver_name("mariadb"), Dialect::Mysql);
        assert_eq!(Dialect::from_driver_name("postgres"), Dialect::Postgres);
        assert_eq!(Dialect::from_driver_name("postgresql"), Dialect::Postgres);
        assert_eq!(Dialect::from_driver_name("sqlite"), Dialect::Unknown);
        assert_eq!(Dialect::from_driver_name(""), Dialect::Unknown);
    }

    #[test]
    fn detect_dialect_recognizes_backtick_as_mysql() {
        assert_eq!(
            detect_dialect("SELECT `id` FROM `users`;"),
            Dialect::Mysql
        );
    }

    #[test]
    fn detect_dialect_recognizes_mysql_markers() {
        let sql = "CREATE TABLE t (id INT AUTO_INCREMENT PRIMARY KEY) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
        assert_eq!(detect_dialect(sql), Dialect::Mysql);
    }

    #[test]
    fn detect_dialect_recognizes_postgres_markers() {
        let sql = "CREATE TABLE t (id SERIAL PRIMARY KEY, data JSONB);";
        assert_eq!(detect_dialect(sql), Dialect::Postgres);
    }

    #[test]
    fn detect_dialect_recognizes_pg_cast() {
        let sql = "SELECT 1::int;";
        assert_eq!(detect_dialect(sql), Dialect::Postgres);
    }

    #[test]
    fn detect_dialect_unknown_for_generic_sql() {
        let sql = "SELECT 1;";
        assert_eq!(detect_dialect(sql), Dialect::Unknown);
    }

    #[test]
    fn normalize_for_same_dialect_is_passthrough() {
        let sql = "SELECT `id` FROM `t`;";
        assert_eq!(
            normalize_for(sql, Dialect::Mysql, Dialect::Mysql),
            sql
        );
    }

    #[test]
    fn normalize_for_unknown_source_is_passthrough() {
        let sql = "SELECT 1;";
        assert_eq!(
            normalize_for(sql, Dialect::Unknown, Dialect::Postgres),
            sql
        );
    }

    #[test]
    fn mysql_to_pg_rewrites_backticks_to_double_quotes() {
        let sql = "SELECT `id`, `name` FROM `users`;";
        let out = normalize_for(sql, Dialect::Mysql, Dialect::Postgres);
        assert!(out.contains("\"id\""), "out = {out}");
        assert!(out.contains("\"users\""), "out = {out}");
        assert!(!out.contains('`'), "out = {out}");
    }

    #[test]
    fn mysql_to_pg_preserves_backticks_inside_strings() {
        // Dentro de 'string literal' os backticks não são identificadores
        // e precisam ficar intocados.
        let sql = "SELECT 'a `backtick` inside' FROM t;";
        let out = normalize_for(sql, Dialect::Mysql, Dialect::Postgres);
        assert!(
            out.contains("'a `backtick` inside'"),
            "out = {out}"
        );
    }

    #[test]
    fn mysql_to_pg_strips_engine_and_charset() {
        let sql = "CREATE TABLE t (id INT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
        let out = normalize_for(sql, Dialect::Mysql, Dialect::Postgres);
        assert!(!out.to_uppercase().contains("ENGINE"), "out = {out}");
        assert!(!out.to_uppercase().contains("CHARSET"), "out = {out}");
    }

    #[test]
    fn mysql_to_pg_remaps_tinyint1_to_boolean() {
        let sql = "CREATE TABLE t (flag TINYINT(1));";
        let out = normalize_for(sql, Dialect::Mysql, Dialect::Postgres);
        assert!(out.to_uppercase().contains("BOOLEAN"), "out = {out}");
    }

    #[test]
    fn mysql_to_pg_remaps_blob_to_bytea() {
        let sql = "CREATE TABLE t (data LONGBLOB);";
        let out = normalize_for(sql, Dialect::Mysql, Dialect::Postgres);
        assert!(out.to_uppercase().contains("BYTEA"), "out = {out}");
    }

    #[test]
    fn mysql_to_pg_auto_increment_becomes_identity() {
        let sql = "CREATE TABLE t (id BIGINT(20) AUTO_INCREMENT PRIMARY KEY);";
        let out = normalize_for(sql, Dialect::Mysql, Dialect::Postgres);
        assert!(
            out.to_uppercase()
                .contains("GENERATED BY DEFAULT AS IDENTITY"),
            "out = {out}"
        );
    }

    #[test]
    fn mysql_to_pg_drops_lock_tables() {
        let sql = "LOCK TABLES `t` WRITE; INSERT INTO `t` VALUES (1); UNLOCK TABLES;";
        let out = normalize_for(sql, Dialect::Mysql, Dialect::Postgres);
        assert!(!out.to_uppercase().contains("LOCK TABLES"), "out = {out}");
        assert!(!out.to_uppercase().contains("UNLOCK TABLES"), "out = {out}");
    }

    #[test]
    fn mysql_to_pg_converts_backslash_quote_escape() {
        let sql = "INSERT INTO t VALUES ('it\\'s');";
        let out = normalize_for(sql, Dialect::Mysql, Dialect::Postgres);
        assert!(out.contains("'it''s'"), "out = {out}");
    }

    #[test]
    fn pg_to_mysql_rewrites_identifiers_to_backticks() {
        let sql = "SELECT \"id\" FROM \"users\";";
        let out = normalize_for(sql, Dialect::Postgres, Dialect::Mysql);
        assert!(out.contains("`id`"), "out = {out}");
        assert!(out.contains("`users`"), "out = {out}");
    }

    #[test]
    fn pg_to_mysql_preserves_single_quoted_strings() {
        let sql = "SELECT 'with a \"quote\" in it';";
        let out = normalize_for(sql, Dialect::Postgres, Dialect::Mysql);
        assert!(out.contains("'with a \"quote\" in it'"), "out = {out}");
    }

    #[test]
    fn pg_to_mysql_serial_becomes_auto_increment() {
        let sql = "CREATE TABLE t (id SERIAL PRIMARY KEY);";
        let out = normalize_for(sql, Dialect::Postgres, Dialect::Mysql);
        assert!(out.to_uppercase().contains("INT"), "out = {out}");
        assert!(
            out.to_uppercase().contains("AUTO_INCREMENT"),
            "out = {out}"
        );
    }

    #[test]
    fn pg_to_mysql_remaps_bytea_to_blob() {
        let sql = "CREATE TABLE t (data BYTEA);";
        let out = normalize_for(sql, Dialect::Postgres, Dialect::Mysql);
        assert!(out.to_uppercase().contains("BLOB"), "out = {out}");
    }

    #[test]
    fn pg_to_mysql_strips_casts() {
        let sql = "SELECT id::int, name::text FROM t;";
        let out = normalize_for(sql, Dialect::Postgres, Dialect::Mysql);
        assert!(!out.contains("::"), "out = {out}");
    }

    #[test]
    fn pg_to_mysql_drops_set_search_path() {
        let sql = "SET search_path TO public; SELECT 1;";
        let out = normalize_for(sql, Dialect::Postgres, Dialect::Mysql);
        assert!(!out.to_uppercase().contains("SEARCH_PATH"), "out = {out}");
    }
}
